<?php

use App\Http\Controllers\Api\V1\Auth\RegisterController;
use App\Http\Controllers\Api\V1\Auth\LoginController;
use App\Http\Controllers\Api\V1\Auth\LogoutController;
use App\Http\Controllers\Api\V1\Doctor\DoctorController;
use App\Http\Controllers\Api\V1\DoctorReview\DoctorReviewController;
use App\Http\Controllers\Api\V1\Invoice\InvoiceController;
use App\Http\Controllers\Api\V1\Patient\PatientController;
use App\Http\Controllers\Api\V1\Appointment\AppointmentController;
use App\Http\Controllers\Api\V1\Payment\PaymentController;
use App\Http\Controllers\Api\V1\Prescription\PrescriptionController;
use App\Http\Controllers\Api\V1\Visit\VisitController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::get('/user', function (Request $request) {
    return $request->user();
})->middleware('auth:sanctum');

Route::prefix('v1')->group(function () {

    Route::prefix('auth')->group(function () {
        Route::post('register', RegisterController::class);
        Route::post('login', LoginController::class)->middleware(['throttle:5,1']);
        Route::post('logout', LogoutController::class)->middleware(['auth:sanctum']);
    });
    // will be handled later on
    Route::middleware(['auth:sanctum', 'role:admin'])->group(function () {
        Route::apiResource('payments', PaymentController::class);
        Route::apiResource('invoices', InvoiceController::class);

        Route::get('/admin/users', [\App\Http\Controllers\Api\V1\Admin\AdminUserController::class, 'index']);
        Route::get('/admin/users/{user}', [\App\Http\Controllers\Api\V1\Admin\AdminUserController::class, 'show']);
        Route::delete('/admin/users/{user}', [\App\Http\Controllers\Api\V1\Admin\AdminUserController::class, 'destroy']);
        Route::post('/admin/users', [\App\Http\Controllers\Api\V1\Admin\AdminUserController::class, 'store']);
        Route::put('/admin/users/{user}', [\App\Http\Controllers\Api\V1\Admin\AdminUserController::class, 'update']);
    });

    Route::middleware(['auth:sanctum', 'role:doctor'])->group(function () {
        // appointments — ID comes from token, not URL
        Route::get('doctor/appointments', [AppointmentController::class, 'index']);
        Route::get('appointments/{id}', [AppointmentController::class, 'show']);

        // visits
        Route::post('appointments/{id}/visits', [VisitController::class, 'store']);
        Route::get('visits/{id}', [VisitController::class, 'show']);
        Route::put('visits/{id}', [VisitController::class, 'update']);

        // prescriptions
        Route::get('visits/{id}/prescriptions', [PrescriptionController::class, 'index']);
        Route::post('visits/{id}/prescriptions', [PrescriptionController::class, 'store']);
        Route::put('prescriptions/{id}', [PrescriptionController::class, 'update']);
        Route::delete('prescriptions/{id}', [PrescriptionController::class, 'destroy']);

        // patients (read-only)
        Route::get('patients/{id}', [PatientController::class, 'show']);
        Route::get('patients/{id}/visits', [PatientController::class, 'visits']);
    });

    Route::middleware(['auth:sanctum', 'role:receptionist'])->group(function () {
        // appointments — no store, no destroy
        Route::get('appointments', [AppointmentController::class, 'index']);
        Route::get('appointments/{id}', [AppointmentController::class, 'show']);
        Route::put('appointments/{id}', [AppointmentController::class, 'update']);
        // update here means: confirm, reject, mark checked-in, mark no-show

        // invoices — read only, auto-generated by system
        Route::get('invoices', [InvoiceController::class, 'index']);
        Route::get('invoices/{id}', [InvoiceController::class, 'show']);

        // payments — receptionist records payments only
        Route::post('payments', [PaymentController::class, 'store']);
    });

    Route::middleware(['auth:sanctum', 'role:patient'])->group(function () {

        // appointments
        Route::get('patient/appointments', [AppointmentController::class, 'index']);
        Route::post('patient/appointments', [AppointmentController::class, 'store']);
        Route::get('patient/appointments/{id}', [AppointmentController::class, 'show']);
        Route::put('patient/appointments/{id}', [AppointmentController::class, 'update']);
        // update handles cancellation (status → cancelled), no destroy

        // invoices — read only
        Route::get('patient/invoices', [InvoiceController::class, 'index']);
        Route::get('patient/invoices/{id}', [InvoiceController::class, 'show']);

        // doctor reviews
        Route::get('doctors/{id}/reviews', [DoctorReviewController::class, 'index']);
        Route::post('doctors/{id}/reviews', [DoctorReviewController::class, 'store']);
        Route::put('reviews/{id}', [DoctorReviewController::class, 'update']);
        Route::delete('reviews/{id}', [DoctorReviewController::class, 'destroy']);
    });

});
